version: "3.9"

services:
  camel_app:
    build: .
    container_name: camel_spring_app
    volumes:
      # Mount host folder so Camel can pick up new JSON files
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=
    restart: unless-stopped